// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: specs/specs.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineSpec is stored in Omni in the infra provisioner state.
type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // required?
	SchematicId   string                 `protobuf:"bytes,2,opt,name=schematic_id,json=schematicId,proto3" json:"schematic_id,omitempty"`
	TalosVersion  string                 `protobuf:"bytes,3,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	VmVolName     string                 `protobuf:"bytes,10,opt,name=vm_vol_name,json=vmVolName,proto3" json:"vm_vol_name,omitempty"`
	PoolName      string                 `protobuf:"bytes,20,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	VmName        string                 `protobuf:"bytes,21,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Datacenter    string                 `protobuf:"bytes,22,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MachineSpec) GetSchematicId() string {
	if x != nil {
		return x.SchematicId
	}
	return ""
}

func (x *MachineSpec) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *MachineSpec) GetVmVolName() string {
	if x != nil {
		return x.VmVolName
	}
	return ""
}

func (x *MachineSpec) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *MachineSpec) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *MachineSpec) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

var File_specs_specs_proto protoreflect.FileDescriptor

const file_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x11specs/specs.proto\x12\bemuspecs\"\xdf\x01\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fschematic_id\x18\x02 \x01(\tR\vschematicId\x12#\n" +
	"\rtalos_version\x18\x03 \x01(\tR\ftalosVersion\x12\x1e\n" +
	"\vvm_vol_name\x18\n" +
	" \x01(\tR\tvmVolName\x12\x1b\n" +
	"\tpool_name\x18\x14 \x01(\tR\bpoolName\x12\x17\n" +
	"\avm_name\x18\x15 \x01(\tR\x06vmName\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x16 \x01(\tR\n" +
	"datacenterB=Z;github.com/siderolabs/omni-infra-provider-vsphere/api/specsb\x06proto3"

var (
	file_specs_specs_proto_rawDescOnce sync.Once
	file_specs_specs_proto_rawDescData []byte
)

func file_specs_specs_proto_rawDescGZIP() []byte {
	file_specs_specs_proto_rawDescOnce.Do(func() {
		file_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)))
	})
	return file_specs_specs_proto_rawDescData
}

var file_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: emuspecs.MachineSpec
}
var file_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_specs_proto_init() }
func file_specs_specs_proto_init() {
	if File_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_specs_proto_rawDesc), len(file_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_specs_specs_proto_goTypes,
		DependencyIndexes: file_specs_specs_proto_depIdxs,
		MessageInfos:      file_specs_specs_proto_msgTypes,
	}.Build()
	File_specs_specs_proto = out.File
	file_specs_specs_proto_goTypes = nil
	file_specs_specs_proto_depIdxs = nil
}
